### ISSUE TITLE
Move swift primary storage to an app of its own

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/files_primary_swift#1]
## Current Situation
the swift implementation lives in core https://github.com/owncloud/core/blob/master/lib/private/Files/ObjectStore/Swift.php and relies on rackspace libraries which are for sure outdated.

## Todo
- [x] move swift.php into this repo
- [x] move the continuous integration in here https://github.com/owncloud/core/blob/master/Jenkinsfile#L115-L127
- [ ] require new rackspace library - mind the guzzle gap
- [ ] add makefile to allow app bundling
- [ ] create signature
- [ ] upload to marketplace
- [ ] remove from master
- [ ] remove from stable10

## Motivation
- allow own release cycle via marketplace
- shrink core
- reduce ci time

**Comment by mrow4a** [comment]
@DeepDiver1975 will have a look

**Comment by mrow4a** [comment]
https://github.com/owncloud/files_primary_swift/pull/3

**Comment by PVince81** [comment]
added items:
- remove from master
- remove from stable10

**Comment by PVince81** [comment]
moving to backlog
